name: Gradle build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle stuff
        uses: actions/cache@v3
        with:
          key: gradle-${{ hashFiles('*.gradle.kts', 'gradle.properties', 'gradle/**', 'versions/*') }}
          restore-keys: |
            gradle-${{ hashFiles('*.gradle.kts', 'gradle.properties', 'gradle/**', 'versions/*') }}
            gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: versions/*/build/libs/
